# Copyright (c) 2017 Microsoft Corporation.
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
# documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
#  rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all copies or substantial portions of
# the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO
# THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
#  TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
# ===================================================================================================================

version: '3'
services:
  malmo1:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo2:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo3:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo4:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo5:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo6:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo7:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo8:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo9:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo10:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo11:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo12:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo13:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo14:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo15:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo16:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo17:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo18:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo19:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo20:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo21:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo22:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo23:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo24:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo25:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo26:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo27:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo28:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo29:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo30:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo31:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  malmo32:
    image: onlytailei/malmo:latest
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.hostname == worker
  agents:
    image: onlytailei/malmopy-pytorch-cpu:latest
    volumes: 
      - /home/tai/malmo_tai/malmo-challenge:/root/malmo-challenge
      - malmo_volume:/root/malmo_save
    working_dir: /root/malmo-challenge/ai_challenge/pig_chase
    entrypoint: /bin/bash
    command: /root/malmo-challenge/ai_challenge/pig_chase/start.sh
    ports:
      - "8097:8097"
    networks:
      - malmo_net
    deploy:
      placement:
        constraints:
          - node.role == manager

networks:
  malmo_net:
    external: true
volumes:
  malmo_volume:
    external: true
